title: Wen Transparency
author: surfcoderepeat
email: surfcoderepeat@protonmail.com
description: Analyzing ICOs finances
baseurl: ""
url: "https://surfer77.github.io/wen-transparency/"

# Build settings
markdown: kramdown